/*
 * Exaroton API
 *
 * HTTP API for exaroton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigFileOptionValue {
    String(String),
    Integer(i32),
    Boolean(bool),
}

impl Default for ConfigFileOptionValue {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

