/*
 * Exaroton API
 *
 * HTTP API for exaroton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreditPoolMember {
    /// Unique account ID of the pool member
    #[serde(rename = "account", skip_serializing_if = "Option::is_none")]
    pub account: Option<String>,
    /// Account name of the pool member
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Share of the credits in this pool that are owned by the account
    #[serde(rename = "share", skip_serializing_if = "Option::is_none")]
    pub share: Option<f64>,
    /// Number of credits in the pool that are owned by the account
    #[serde(rename = "credits", skip_serializing_if = "Option::is_none")]
    pub credits: Option<f64>,
    /// Whether the account is the owner of this credit pool
    #[serde(rename = "isOwner", skip_serializing_if = "Option::is_none")]
    pub is_owner: Option<bool>,
}

impl CreditPoolMember {
    pub fn new() -> CreditPoolMember {
        CreditPoolMember {
            account: None,
            name: None,
            share: None,
            credits: None,
            is_owner: None,
        }
    }
}

