/*
 * Exaroton API
 *
 * HTTP API for exaroton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreditPool {
    /// Unique credit pool ID
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Credit pool name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Credits in this credit pool
    #[serde(rename = "credits", skip_serializing_if = "Option::is_none")]
    pub credits: Option<f64>,
    /// Number of servers in this credit pool
    #[serde(rename = "servers", skip_serializing_if = "Option::is_none")]
    pub servers: Option<i32>,
    /// Unique account ID of the pool owner
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<String>,
    /// Whether the current user is the owner of this credit pool
    #[serde(rename = "isOwner", skip_serializing_if = "Option::is_none")]
    pub is_owner: Option<bool>,
    /// Number of members in this credit pool
    #[serde(rename = "members", skip_serializing_if = "Option::is_none")]
    pub members: Option<i32>,
    /// Share of the credits in this pool that are owned by the current user
    #[serde(rename = "ownShare", skip_serializing_if = "Option::is_none")]
    pub own_share: Option<f64>,
    /// Number of credits in the pool that are owned by the current user
    #[serde(rename = "ownCredits", skip_serializing_if = "Option::is_none")]
    pub own_credits: Option<f64>,
}

impl CreditPool {
    pub fn new() -> CreditPool {
        CreditPool {
            id: None,
            name: None,
            credits: None,
            servers: None,
            owner: None,
            is_owner: None,
            members: None,
            own_share: None,
            own_credits: None,
        }
    }
}

