/*
 * Exaroton API
 *
 * HTTP API for exaroton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeletePlayerListRequestBody {
    #[serde(rename = "entries", skip_serializing_if = "Option::is_none")]
    pub entries: Option<Vec<String>>,
}

impl DeletePlayerListRequestBody {
    pub fn new() -> DeletePlayerListRequestBody {
        DeletePlayerListRequestBody {
            entries: None,
        }
    }
}

