/*
 * Exaroton API
 *
 * HTTP API for exaroton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExtendServerStopTimeRequestBody {
    /// Number of seconds to extend the stop timer by
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<i32>,
}

impl ExtendServerStopTimeRequestBody {
    pub fn new() -> ExtendServerStopTimeRequestBody {
        ExtendServerStopTimeRequestBody {
            time: None,
        }
    }
}

