/*
 * Exaroton API
 *
 * HTTP API for exaroton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileInfo {
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "isTextFile", skip_serializing_if = "Option::is_none")]
    pub is_text_file: Option<bool>,
    #[serde(rename = "isConfigFile", skip_serializing_if = "Option::is_none")]
    pub is_config_file: Option<bool>,
    #[serde(rename = "isDirectory", skip_serializing_if = "Option::is_none")]
    pub is_directory: Option<bool>,
    #[serde(rename = "isLog", skip_serializing_if = "Option::is_none")]
    pub is_log: Option<bool>,
    #[serde(rename = "isReadable", skip_serializing_if = "Option::is_none")]
    pub is_readable: Option<bool>,
    #[serde(rename = "isWritable", skip_serializing_if = "Option::is_none")]
    pub is_writable: Option<bool>,
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
    #[serde(rename = "children", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub children: Option<Option<Vec<models::FileInfo>>>,
}

impl FileInfo {
    pub fn new() -> FileInfo {
        FileInfo {
            path: None,
            name: None,
            is_text_file: None,
            is_config_file: None,
            is_directory: None,
            is_log: None,
            is_readable: None,
            is_writable: None,
            size: None,
            children: None,
        }
    }
}

