/*
 * Exaroton API
 *
 * HTTP API for exaroton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAccount200ResponseData {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "verified", skip_serializing_if = "Option::is_none")]
    pub verified: Option<bool>,
    #[serde(rename = "credits", skip_serializing_if = "Option::is_none")]
    pub credits: Option<f64>,
}

impl GetAccount200ResponseData {
    pub fn new() -> GetAccount200ResponseData {
        GetAccount200ResponseData {
            name: None,
            email: None,
            verified: None,
            credits: None,
        }
    }
}

