/*
 * Exaroton API
 *
 * HTTP API for exaroton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetServerLog200ResponseData {
    #[serde(rename = "content", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub content: Option<Option<String>>,
}

impl GetServerLog200ResponseData {
    pub fn new() -> GetServerLog200ResponseData {
        GetServerLog200ResponseData {
            content: None,
        }
    }
}

