/*
 * Exaroton API
 *
 * HTTP API for exaroton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetServerRam200ResponseData {
    /// How many GB ram this server has
    #[serde(rename = "ram", skip_serializing_if = "Option::is_none")]
    pub ram: Option<i32>,
}

impl GetServerRam200ResponseData {
    pub fn new() -> GetServerRam200ResponseData {
        GetServerRam200ResponseData {
            ram: None,
        }
    }
}

