/*
 * Exaroton API
 *
 * HTTP API for exaroton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetServerMotd200ResponseData {
    /// The MOTD of the server
    #[serde(rename = "motd", skip_serializing_if = "Option::is_none")]
    pub motd: Option<String>,
}

impl GetServerMotd200ResponseData {
    pub fn new() -> GetServerMotd200ResponseData {
        GetServerMotd200ResponseData {
            motd: None,
        }
    }
}

