/*
 * Exaroton API
 *
 * HTTP API for exaroton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostServerRamRequest {
    /// How many GB ram this server should have
    #[serde(rename = "ram")]
    pub ram: i32,
}

impl PostServerRamRequest {
    pub fn new(ram: i32) -> PostServerRamRequest {
        PostServerRamRequest {
            ram,
        }
    }
}

