/*
 * Exaroton API
 *
 * HTTP API for exaroton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostStartServerRequest {
    #[serde(rename = "useOwnCredits", skip_serializing_if = "Option::is_none")]
    pub use_own_credits: Option<bool>,
}

impl PostStartServerRequest {
    pub fn new() -> PostStartServerRequest {
        PostStartServerRequest {
            use_own_credits: None,
        }
    }
}

