/*
 * Exaroton API
 *
 * HTTP API for exaroton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostServerCommandRequestBody {
    /// The command to send to the server
    #[serde(rename = "command", skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
}

impl PostServerCommandRequestBody {
    pub fn new() -> PostServerCommandRequestBody {
        PostServerCommandRequestBody {
            command: None,
        }
    }
}

