/*
 * Exaroton API
 *
 * HTTP API for exaroton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostServerMotdRequest {
    /// The new MOTD for the server
    #[serde(rename = "motd")]
    pub motd: String,
}

impl PostServerMotdRequest {
    pub fn new(motd: String) -> PostServerMotdRequest {
        PostServerMotdRequest {
            motd,
        }
    }
}

