/*
 * Exaroton API
 *
 * HTTP API for exaroton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerPlayers {
    /// Maximum player count (slots)
    #[serde(rename = "max", skip_serializing_if = "Option::is_none")]
    pub max: Option<i32>,
    /// Current player count
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// Current player list (not always available)
    #[serde(rename = "list", skip_serializing_if = "Option::is_none")]
    pub list: Option<Vec<String>>,
}

impl ServerPlayers {
    pub fn new() -> ServerPlayers {
        ServerPlayers {
            max: None,
            count: None,
            list: None,
        }
    }
}

