/*
 * Exaroton API
 *
 * HTTP API for exaroton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ServerSoftware : Information about the installed server software
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerSoftware {
    /// Unique software ID
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Software name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Software version
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl ServerSoftware {
    /// Information about the installed server software
    pub fn new() -> ServerSoftware {
        ServerSoftware {
            id: None,
            name: None,
            version: None,
        }
    }
}

