/*
 * Exaroton API
 *
 * HTTP API for exaroton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Serialize_repr,Deserialize_repr};
/// ServerStatus : Servers can have different numeric status codes. Depending on a server's status, only certain features might be available. Possible enum values:  * 0 = OFFLINE  * 1 = ONLINE  * 2 = STARTING  * 3 = STOPPING  * 4 = RESTARTING  * 5 = SAVING  * 6 = LOADING  * 7 = CRASHED  * 8 = PENDING  * 9 = TRANSFERRING  * 10 = PREPARING 
/// Servers can have different numeric status codes. Depending on a server's status, only certain features might be available. Possible enum values:  * 0 = OFFLINE  * 1 = ONLINE  * 2 = STARTING  * 3 = STOPPING  * 4 = RESTARTING  * 5 = SAVING  * 6 = LOADING  * 7 = CRASHED  * 8 = PENDING  * 9 = TRANSFERRING  * 10 = PREPARING 
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum ServerStatus {
    OFFLINE = 0,
    ONLINE = 1,
    STARTING = 2,
    STOPPING = 3,
    RESTARTING = 4,
    SAVING = 5,
    LOADING = 6,
    CRASHED = 7,
    PENDING = 8,
    TRANSFERRING = 9,
    PREPARING = 10,

}

impl std::fmt::Display for ServerStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::OFFLINE => "0",
            Self::ONLINE => "1",
            Self::STARTING => "2",
            Self::STOPPING => "3",
            Self::RESTARTING => "4",
            Self::SAVING => "5",
            Self::LOADING => "6",
            Self::CRASHED => "7",
            Self::PENDING => "8",
            Self::TRANSFERRING => "9",
            Self::PREPARING => "10",
        })
    }
}
impl Default for ServerStatus {
    fn default() -> ServerStatus {
        Self::OFFLINE
    }
}

