/*
 * Exaroton API
 *
 * HTTP API for exaroton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Server {
    /// Unique server ID
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Server name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Full server address
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// The MOTD of the server
    #[serde(rename = "motd", skip_serializing_if = "Option::is_none")]
    pub motd: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::ServerStatus>,
    /// Host machine the server is running on. Only available if the server is online.
    #[serde(rename = "host", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub host: Option<Option<String>>,
    /// Port the server is listening on. Only available if the server is online.
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<i32>,
    #[serde(rename = "players", skip_serializing_if = "Option::is_none")]
    pub players: Option<Box<models::ServerPlayers>>,
    #[serde(rename = "software", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub software: Option<Option<Box<models::ServerSoftware>>>,
    /// Whether the server is accessed via the Share Access feature
    #[serde(rename = "shared", skip_serializing_if = "Option::is_none")]
    pub shared: Option<bool>,
}

impl Server {
    pub fn new() -> Server {
        Server {
            id: None,
            name: None,
            address: None,
            motd: None,
            status: None,
            host: None,
            port: None,
            players: None,
            software: None,
            shared: None,
        }
    }
}

