/*
 * Exaroton API
 *
 * HTTP API for exaroton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShareServerLog200ResponseData {
    /// ID on mclo.gs
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// URL to shared logs on mclo.gs
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// URL to api of mclo.gs
    #[serde(rename = "raw", skip_serializing_if = "Option::is_none")]
    pub raw: Option<String>,
}

impl ShareServerLog200ResponseData {
    pub fn new() -> ShareServerLog200ResponseData {
        ShareServerLog200ResponseData {
            id: None,
            url: None,
            raw: None,
        }
    }
}

